application: join-stuykc
version: 1
runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- warmup

skip_files:
- ^(.*/)?.*\.pyc

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: join/static/favicon.ico
  upload: join/static/favicon\.ico
  expiration: 7d
- url: /(apple-touch-icon.*\.(png))
  static_files: join/static/\1
  upload: join/static/(apple-touch-icon.*\.png)
  expiration: 7d
- url: /images
  static_dir: join/static/images
  expiration: 7d
- url: /css
  static_dir: join/static/css
  expiration: 3d
- url: /js
  static_dir: join/static/js
  expiration: 3d
- url: /.*
  script: join.views.application
