application: join-stuykc
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?.*\.pyc

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: join/static/images
  expiration: 3d
- url: /css
  static_dir: join/static/css
  expiration: 12h
- url: /js
  static_dir: join/static/js
  expiration: 1d
- url: /.*
  script: join.views.application
